code/IBV.EDC/IBV.EDC.Web/Controllers/FrequentlyAskedQuestionsController.cs
using IBV.EDC.Lib.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web;

namespace IBV.EDC.Web.Controllers
{
    public class FrequentlyAskedQuestionsController : BaseSurfaceController
    {
        public ActionResult FAQGroupList()
        {
            return PartialView("_FAQGroupList", FaqGroupList.Get(CurrentPage.GetPropertyValue<IEnumerable<IPublishedContent>>("faqGroupList")));
        }
    }
}

code/IBV.EDC/IBV.EDC.Web/Controllers/GatewayController.cs
using System.Web.Mvc;

namespace IBV.EDC.Web.Controllers
{
    public class GatewayController : BaseSurfaceController
    {
        // ACTIONS
        public ActionResult GridResults()
        {
            return PartialView("_GridResults", SearchResultList);
        }
    }
}

code/IBV.EDC/IBV.EDC.Web/Controllers/GeneralArticleController.cs
using Archetype.Models;
using IBV.EDC.Lib.Models;
using IBV.EDC.Web.ViewModels;
using System.Collections.Generic;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web;
using System.Linq;

namespace IBV.EDC.Web.Controllers
{
    public class GeneralArticleController : BaseSurfaceController
    {
        public ActionResult Faq()
        {
            return PartialView("_Faq", FaqList.Get(CurrentPage.GetPropertyValue<IEnumerable<IPublishedContent>>("faq")));
        }

        public ActionResult Features()
        {
            return PartialView("_Features", FeatureList.Get(CurrentPage.GetPropertyValue<IEnumerable<IPublishedContent>>("features")));
        }


        public ActionResult GroupedLinks(string linksPropertyName, string headingPropertyName)
        {
            GroupedLinkListViewModel model = new GroupedLinkListViewModel()
            {
                Heading = CurrentPage.GetPropertyValue<string>(headingPropertyName),
                GroupedLinks = CurrentPage.GetPropertyValue<ArchetypeModel>(linksPropertyName)
                                        .Fieldsets
                                        .Select(x => new CategoryLinkListViewModel
                                                {
                                                    Category = x.GetValue<string>("categoryHeading"),
                                                    GroupedLinks = LinkList.Get(x.GetValue<IEnumerable<IPublishedContent>>("categoryLinks"))
                                                })
                                        .ToList()
            };

            return PartialView("_GroupedLinks", model);
        }

        public ActionResult SideFeatures()
        {
            return PartialView("_SideFeatures", FeatureList.Get(CurrentPage.GetPropertyValue<IEnumerable<IPublishedContent>>("sideFeatures")));
        }
    }
}

code/IBV.EDC/IBV.EDC.Web/Controllers/ListController.cs
using System.Web.Mvc;

namespace IBV.EDC.Web.Controllers
{
    public class ListController : BaseSurfaceController
    {
        [ChildActionOnly]
        public ActionResult ListFilters()
        {
            return PartialView("_ListFilters", SearchFilters);
        }

        [ChildActionOnly]
        public ActionResult ListFiltersCheckbox()
        {
            return PartialView("_ListFiltersCheckbox", SearchFilters);
        }

        [HttpPost]
        public ActionResult SubmitFiltersCheckbox(FormCollection formCollection)
        {
            return CurrentUmbracoPage();
        }

        [ChildActionOnly]
        public ActionResult ListFiltersSide()
        {
            return PartialView("_ListFiltersSide", SearchFilters);
        }

        [ChildActionOnly]
        public ActionResult ListResults()
        {
            return PartialView("_ListResults", SearchResultList);
        }

        [ChildActionOnly]
        public ActionResult ListResultsDocuments()
        {
            return PartialView("_ListResultsDocuments", SearchResultList);
        }

        [ChildActionOnly]
        public ActionResult ListResultsEvents()
        {
            return PartialView("_ListResultsEvents", SearchResultList);
        }

        [ChildActionOnly]
        public ActionResult ListResultsGrid(bool ignoreDates = false)
        {
            ViewBag.IgnoreDates = ignoreDates;
            return PartialView("_ListResultsGrid", SearchResultList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ListResultsPost(FormCollection formCollection)
        {
            return CurrentUmbracoPage();
        }

        [ChildActionOnly]
        public ActionResult Pager()
        {
            return PartialView("_Pager", SearchPager);
        }
    }
}

code/IBV.EDC/IBV.EDC.Web/Controllers/NewsArticleController.cs
using IBV.EDC.Lib.Models;
using System;
using System.Web.Mvc;
using Umbraco.Web;

namespace IBV.EDC.Web.Controllers
{
    public class NewsArticleController : BaseSurfaceController
    {
        public ActionResult ArticleDate()
        {
            return PartialView("_ArticleDate", Date.Get(CurrentPage.GetPropertyValue<DateTime>("nodeDate")));
        }

        public ActionResult LinkToParent()
        {
            return PartialView("_LinkToParent", Link.Get(CurrentPage.Parent));
        }
    }
}

code/IBV.EDC/IBV.EDC.Web/Controllers/SharedController.cs
using IBV.EDC.Lib.Domain;
using IBV.EDC.Lib.Models;
using IBV.EDC.Lib.Models.Interfaces;
using IBV.EDC.Lib.Tools;
using IBV.EDC.Web.ViewModels;
using nuPickers;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web;

namespace IBV.EDC.Web.Controllers
{
    public class SharedController : BaseSurfaceController
    {
        [ChildActionOnly]
        public ActionResult BodyCloseCode()
        {
            return PartialView("_RawCode", LayoutNode.GetPropertyValue<string>("bodyCloseCode"));
        }

        [ChildActionOnly]
        public ActionResult BodyOpenCode()
        {
            return PartialView("_RawCode", LayoutNode.GetPropertyValue<string>("bodyOpenCode"));
        }

        [ChildActionOnly]
        public ActionResult BreadcrumbTrail()
        {
            return PartialView("_BreadcrumbTrail", Breadcrumb.Get());
        }

        [ChildActionOnly]
        public ActionResult Canonical()
        {
            return PartialView("_Canonical", IPublishedContentTools.GetCanonical(CurrentPage));
        }

        [ChildActionOnly]
        public ActionResult Carousel()
        {
            return PartialView("_Carousel", FeatureList.Get(CurrentPage.GetPropertyValue<IEnumerable<IPublishedContent>>("carousel")));
        }

        [ChildActionOnly]
        public ActionResult CookieBar()
        {
            ILink model = Link.Get(ConfigurationNode.GetPropertyValue<IPublishedContent>("siteCookiePolicyPage"));
            return PartialView("_CookieBar", model);
        }

        [ChildActionOnly]
        public ActionResult DisplaySiteAlert()
        {
            var siteAlertNode = IPublishedContentTools.GetSiteAlertNode();
            if (SiteAlert.Display(siteAlertNode))
            {
                SiteAlertViewModel model = new SiteAlertViewModel()
                {
                    AlertText = siteAlertNode.GetPropertyValue<string>("siteAlertText"),
                    AlertLink = siteAlertNode.GetPropertyValue<string>("siteAlertLink"),
                    AlertLinkText = siteAlertNode.GetPropertyValue<string>("siteAlertLinkText")
                };

                return PartialView("_DisplaySiteAlert", model);
            }

            return null;
        }

        [ChildActionOnly]
        public ActionResult EnsureSSL()
        {
            IFlag useHTTPS = Flag.Get(ConfigurationManager.AppSettings.Get("umbracoUseSSL").ToString());
            if (useHTTPS.IsTrue && !HttpContext.Request.IsSecureConnection)
            {
                HttpContext.Response.RedirectPermanent("https://" + Request.Url.Host + Request.RawUrl);
            }

            if (!useHTTPS.IsTrue && HttpContext.Request.IsSecureConnection)
            {
                HttpContext.Response.RedirectPermanent("http://" + Request.Url.Host + Request.RawUrl);
            }

            return null;
        }

        [ChildActionOnly]
        public ActionResult FooterExternalLinks()
        {
            return PartialView("_FooterExternalLinks", LinkList.Get(LayoutNode.GetPropertyValue<IEnumerable<IPublishedContent>>("footerExternalLinks")));
        }

        [ChildActionOnly]
        public ActionResult FooterLinks()
        {
            return PartialView("_FooterLinks", LinkList.Get(LayoutNode.GetPropertyValue<IEnumerable<IPublishedContent>>("footerLinks")));
        }

        [ChildActionOnly]
        public ActionResult FooterLogo()
        {
            return PartialView("_FooterLogo", Image.Get(LayoutNode.GetPropertyValue<IPublishedContent>("footerLogo")));
        }

        [ChildActionOnly]
        public ActionResult FooterText()
        {
            var model = new FooterTextViewModel()
            {
                Heading = !String.IsNullOrWhiteSpace(LayoutNode.GetPropertyValue<string>("footerTextHeading")) ? LayoutNode.GetPropertyValue<string>("footerTextHeading") : "School Address",
                FooterText = LayoutNode.GetPropertyValue<string>("footerText")
            };

            return PartialView("_FooterText", model);
        }

        [ChildActionOnly]
        public ActionResult FooterCopyrightText()
        {
            return PartialView("_FooterCopyrightText", LayoutNode.GetPropertyValue<string>("headerLogoText"));
        }

        [ChildActionOnly]
        public ActionResult GoogleAnalytics()
        {
            return PartialView("_GoogleAnalytics", ConfigurationNode.GetPropertyValue<string>("googleAnalyticsKey"));
        }

        [ChildActionOnly]
        public ActionResult HeadAreaCode()
        {
            return PartialView("_RawCode", LayoutNode.GetPropertyValue<string>("headAreaCode"));
        }

        [ChildActionOnly]
        public ActionResult HeaderExternalLinks()
        {
            return PartialView("_HeaderExternalLinks", LinkList.Get(LayoutNode.GetPropertyValue<IEnumerable<IPublishedContent>>("headerExternalLinks")));
        }

        [ChildActionOnly]
        public ActionResult HeaderSearch()
        {
            ILink model = Link.Get(ConfigurationNode.GetPropertyValue<IPublishedContent>("siteSearchPage"));

            if (model != null)
            {
                return PartialView("_HeaderSearch", model);
            }

            return null;
        }

        [ChildActionOnly]
        public ActionResult HeaderLogo()
        {
            return PartialView("_HeaderLogo", Image.Get(LayoutNode.GetPropertyValue<IPublishedContent>("headerLogo")));
        }

        [ChildActionOnly]
        public ActionResult HeaderLogoText()
        {
            return PartialView("_HeaderLogoText", LayoutNode.GetPropertyValue<string>("headerLogoText"));
        }

        [ChildActionOnly]
        public ActionResult ImageCrop(Image image, ImageCrop lg, ImageCrop md, ImageCrop sm, ImageCrop xs, string attrs = "")
        {
            ImageCropViewModel model = new ImageCropViewModel()
            {
                Image = image,
                Large = lg,
                Medium = md,
                Small = sm,
                ExtraSmall = xs,
                Attributes = attrs
            };

            return PartialView("_ImageCrop", model);
        }

        [ChildActionOnly]
        public ActionResult ImageGallery()
        {
            return PartialView("_ImageGallery", ImageList.Get(CurrentPage.GetPropertyValue<IEnumerable<IPublishedContent>>("ImageGallery")));
        }

        [ChildActionOnly]
        public ActionResult ImageLister()
        {
            return PartialView("_ImageLister", ImageList.Get(CurrentPage.GetPropertyValue<IEnumerable<IPublishedContent>>("ImageGallery")));
        }

        [ChildActionOnly]
        public ActionResult LinkToParent()
        {
            return PartialView("_LinkToParent", Link.Get(CurrentPage.Parent));
        }

        [ChildActionOnly]
        public ActionResult MainNavigation()
        {
            return PartialView("_MainNavigation", Menu.Get(IPublishedContentTools.GetHomeNode(), isSideMenu: false));
        }

        [ChildActionOnly]
        public ActionResult MetaData()
        {
            MetaDataViewModel model = new MetaDataViewModel()
            {
                MetaTitle = String.Format("{0} - {1}", IPublishedContentTools.GetMetaTitle(CurrentPage), IPublishedContentTools.GetHomeNode().Name),
                MetaDescription = IPublishedContentTools.GetMetaDescription(CurrentPage),
                MetaTags = CurrentPage.GetPropertyValue<string>("metaTags")
            };

            return PartialView("_MetaData", model);
        }

        [ChildActionOnly]
        public ActionResult MetaRobots()
        {
            bool noIndex = ConfigurationNode.GetPropertyValue<bool>("noRobotsIndex");

            if (noIndex)
            {
                return PartialView("_MetaRobots", "<meta name=\"robots\" content=\"noindex, nofollow\" />");
            }

            return null;
        }

        [ChildActionOnly]
        public ActionResult PageBanner()
        {
            return PartialView("_PageBanner", Image.Get(CurrentPage.GetPropertyValue<IPublishedContent>("pageBanner")));
        }

        [ChildActionOnly]
        public ActionResult RelatedLinks()
        {
            LinkListViewModel model = new LinkListViewModel()
            {
                Title = CurrentPage.GetPropertyValue<string>("relatedLinksHeading"),
                LinkList = LinkList.Get(CurrentPage.GetPropertyValue<IEnumerable<IPublishedContent>>("relatedLinks"))
            };

            return PartialView("_RelatedLinks", model);
        }

        [ChildActionOnly]
        public ActionResult RelatedMedia()
        {
            LinkListViewModel model = new LinkListViewModel()
            {
                Title = CurrentPage.GetPropertyValue<string>("relatedMediaHeading"),
                LinkList = LinkList.Get(CurrentPage.GetPropertyValue<IEnumerable<IPublishedContent>>("relatedMedia"))
            };

            return PartialView("_RelatedMedia", model);
        }

        [ChildActionOnly]
        public ActionResult Stylesheet()
        {
            var stylesheetNodeId = LayoutNode.GetPropertyValue<Picker>("schoolStylesheet").SavedValue.ToString();
            var cssFileName = SchoolStylesheet.Get(stylesheetNodeId);

            return PartialView("_Stylesheet", cssFileName ?? "douglas-academy.css");
        }

        [ChildActionOnly]
        public ActionResult SubNavigation()
        {
            return PartialView("_SubNavigation", Menu.Get(ignoreRootHiddenStatus: true, isSideMenu: true));
        }
    }
}

code/IBV.EDC/IBV.EDC.Web/Views/Calendar.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using ContentModels = Umbraco.Web.PublishedContentModels;
@using ClientDependency.Core.Mvc;
@{
    Layout = "_Layout.cshtml";

    Html.RequiresCss("~/content/css/vendor/fullcalendar.min.css");
    Html.RequiresCss("~/content/css/vendor/jquery.ui.css");
    Html.RequiresJs("~/Scripts/src/vendor/jquery.ui.min.js", 1);
    Html.RequiresJs("~/Scripts/src/vendor/moment.min.js", 1);
    Html.RequiresJs("~/Scripts/src/vendor/fullcalendar.js", 2);
    Html.RequiresJs("~/Scripts/src/events.js", 3);
    Html.RequiresJs("~/Scripts/src/calendar-views.js", 3);
}


<div class="banner">
    <h1>@Model.Content.Name</h1>
</div>

@Html.Action("BreadcrumbTrail", "Shared")

<style>
    .ui-dialog-titlebar-close {
        display: none !important;
    }
</style>

<div class="calendar with-side-nav">
    <div class="container-2col">
        <div class="grid__col--8">
            @Umbraco.Field("nodeHeading", insertBefore: "<h1>", insertAfter: "</h1>")
            @Umbraco.Field("nodeContent")
            @Html.Action("ListFiltersCheckbox", "List")
            <div id="calendar" class="fc fc-unthemed fc-ltr"></div>
        </div>
        <div class="grid__col--4">
            <div class="side-content">
                @Html.Action("SubNavigation", "Shared")
            </div>
        </div>
    </div>
</div>

<div style="display:none;" id="pageID" data-val="@Umbraco.UmbracoContext.PageId"></div>
<div id="selectedTagFilters" data-tagfilters=""></div>

@* DO NOT REMOVE THE POPUP CONTAINER BELOW. IT IS USED BY THE CALENDAR *@
<div class="calendar-popup" id="calendar-popup">
    <div class="calendar-popup__background">
        <div class="calendar-popup__holder">
            <div class="calendar-popup__popup">
                <div class="calendar-popup__date" id="event-day">05<span>sept</span></div>
                <div class="calendar-popup__content">
                    <h4 id="event-title">Calendar entry, event title could be long...</h4>
                    <p id="event-time"></p>
                    <h5>Event details</h5>
                    <p id="event-details">Diam a parturient condimentum luctus scelerisque netus adipiscing suspendisse moliestie quam eu fringilla suspendisse in varius vestibulum cras habita. Phasellus justo ut a a elementum convallis inceptos.</p>
                    <p id="event-url"></p>
                </div>
                <div class="calendar-popup__close">
                    Close
                    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="30px" height="30px" viewBox="0 0 30 30" enable-background="new 0 0 30 30" xml:space="preserve">
                        <path fill-rule="evenodd" clip-rule="evenodd" fill="#FFF" d="M0,6l6-6l24,24l-6,6L0,6z" />
                        <path fill-rule="evenodd" clip-rule="evenodd" fill="#FFF" d="M6.1,29.9l-5.9-5.9L23.9,0.1l5.9,5.9L6.1,29.9z" />
                    </svg>
                </div>
            </div>
        </div>
    </div>
</div>

code/IBV.EDC/IBV.EDC.Web/Views/ContactForm.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ContactForm>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@using ClientDependency.Core.Mvc
@{
    Layout = "_Layout.cshtml";
}

@{
    Html.RequiresJs("/Scripts/src/send-contact-email.js");
}

<div class="banner">
    <h1>@Model.Content.Name</h1>
</div>
@Html.Action("BreadcrumbTrail", "Shared")

<div class="contact with-side-nav">
    <div class="container-2col">
        <div class="grid__col--8">
            @Umbraco.Field("nodeHeading", insertBefore: "<h1>", insertAfter: "</h1>")
            @Umbraco.Field("nodeContact")
            @Html.Action("Contact")
        </div>
        <div class="grid__col--4">
            <div class="side-content">
                @Umbraco.Field("contactHeading", insertBefore: "<h4>", insertAfter: "</h4>")
                @Umbraco.Field("contactContent")
            </div>
        </div>
    </div>

    @Html.Action("GoogleMap")
</div>



@section BodyClose {
    @{
        Html.RequiresJs("/Scripts/src/google-map.js");
    }
}

code/IBV.EDC/IBV.EDC.Web/Views/Error404.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Error404>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "_Layout.cshtml";
}

<div class="banner-with-svg">
    <div class="banner__holder">
        <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="129px" height="129px" viewBox="0 0 129 129" enable-background="new 0 0 129 129" xml:space="preserve">
            <path fill="#FFFFFF" d="M64.5,2C99,2,127,30,127,64.5S99,127,64.5,127S2,99,2,64.5S30,2,64.5,2 M64.5,0C28.9,0,0,28.9,0,64.5 S28.9,129,64.5,129S129,100.1,129,64.5S100.1,0,64.5,0L64.5,0z" />
            <path fill="#FFFFFF" d="M89.1,93H42V33.9h35.3l11.8,11.6V93z M43.2,91.8h44.6V46L76.8,35.1H43.2V91.8z" />
            <path fill="#FFFFFF" d="M90,46.3H76.4V33L90,46.3z M77.6,45.1H87l-9.4-9.2V45.1z" />
            <path fill-rule="evenodd" clip-rule="evenodd" fill="#FFFFFF" d="M55.6,56.3l0.7-0.7l19.1,19.1l-0.7,0.7L55.6,56.3z" />
            <path fill-rule="evenodd" clip-rule="evenodd" fill="#FFFFFF" d="M56.7,75L56,74.3L75.3,55l0.7,0.7L56.7,75z" />
        </svg>
        <h1>@Model.Content.Name</h1>
    </div>
</div>
@Html.Action("BreadcrumbTrail", "Shared")

<div class="error-404">
    <div class="container">
        <div class="grid__col--9">
            @Umbraco.Field("nodeIntroductionContent")
            @Umbraco.Field("nodeContent")
        </div>
        <div class="grid__col--3">
        </div>
    </div>
</div>

code/IBV.EDC/IBV.EDC.Web/Views/EventArticle.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.EventArticle>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "_Layout.cshtml";
}

<div class="banner">
    <h1>@Model.Content.Name</h1>
</div>
@Html.Action("BreadcrumbTrail", "Shared")

<div class="event-article with-side-nav">
    <div class="container-2col">
        <div class="grid__col--8">
            @Html.Action("ImageGallery", "Shared")

            @Umbraco.Field("nodeHeading", insertBefore: "<h1>", insertAfter: "</h1>")
            @Umbraco.Field("nodeContent")

            @Html.Action("LinkToParent", "Shared")

            <div class="related-content">
                @Html.Action("RelatedLinks", "Shared")
                @Html.Action("RelatedMedia", "Shared")
            </div>
        </div>
        <div class="grid__col--4">
            <div class="side-content">
                @Html.Action("SubNavigation", "Shared")
            </div>
        </div>
    </div>
</div>

code/IBV.EDC/IBV.EDC.Web/Views/FrequentlyAskedQuestions.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.FrequentlyAskedQuestions>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "_Layout.cshtml";
}

<div class="banner">
    <h1>@Model.Content.Name</h1>
</div>
@Html.Action("BreadcrumbTrail", "Shared")

<div class="frequently-asked-questions with-side-nav">
    <div class="container-2col">
        <div class="grid__col--8">
            @Umbraco.Field("nodeHeading", insertBefore: "<h1>", insertAfter: "</h1>")
            @Umbraco.Field("nodeContent")

            @Html.Action("FaqGroupList")
        </div>
        <div class="grid__col--4">
            <div class="side-content">
                @Html.Action("SubNavigation", "Shared")
            </div>
        </div>
    </div>
</div>

code/IBV.EDC/IBV.EDC.Web/Views/Gateway.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Gateway>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "_Layout.cshtml";
}


<div class="banner">
    <h1>@Model.Content.Name</h1>
</div>
@Html.Action("BreadcrumbTrail", "Shared")

<div class="gateway">
    <div class="container">
        @Umbraco.Field("nodeHeading", insertBefore: "<h1>", insertAfter: "</h1>")
        @Umbraco.Field("nodeContent")
    </div>
    
    @Html.Action("GridResults")

    <div class="pager__1col-wrapper">
        @Html.Action("Pager", "List")
    </div>
</div>

code/IBV.EDC/IBV.EDC.Web/Views/ListDocument.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "_Layout.cshtml";
}

<div class="banner">
    <h1>@Model.Content.Name</h1>
</div>
@Html.Action("BreadcrumbTrail", "Shared")

<div class="list-results with-side-nav">
    <div class="container-2col">
        <div class="grid__col--8">
            @Umbraco.Field("nodeHeading", insertBefore: "<h1>", insertAfter: "</h1>")
            @Umbraco.Field("nodeContent")

            @Html.Action("ListResultsDocuments", "List")
            @Html.Action("Pager", "List")
        </div>
        <div class="grid__col--4">
            <div class="side-content">
                @Html.Action("SubNavigation", "Shared")
            </div>
        </div>
    </div>
</div>

code/IBV.EDC/IBV.EDC.Web/Views/ListEvent.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "_Layout.cshtml";
}

<div class="banner">
    <h1>@Model.Content.Name</h1>
</div>

@Html.Action("BreadcrumbTrail", "Shared")

<div class="list-results with-side-nav">
    <div class="container-2col">
        <div class="grid__col--8">
            @Umbraco.Field("nodeHeading", insertBefore: "<h1>", insertAfter: "</h1>")
            @Html.Action("ListFiltersCheckbox", "List")

            @Html.Action("ListResultsEvents", "List")
            @Html.Action("Pager", "List")
        </div>
        <div class="grid__col--4">
            <div class="side-content">
                @Html.Action("SubNavigation", "Shared")
            </div>
        </div>
    </div>
</div>

code/IBV.EDC/IBV.EDC.Web/Views/ListNews.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "_Layout.cshtml";
}

<div class="banner">
    <h1>@Model.Content.Name</h1>
</div>

@Html.Action("BreadcrumbTrail", "Shared")

<div class="list-results with-side-nav">
    <div class="container-2col">
        <div class="grid__col--8">
            @Umbraco.Field("nodeHeading", insertBefore: "<h1>", insertAfter: "</h1>")
            @Html.Action("ListFiltersCheckbox", "List")

            @Html.Action("ListResultsGrid", "List")
            @Html.Action("Pager", "List")
        </div>
        <div class="grid__col--4">
            <div class="side-content">
                @Html.Action("SubNavigation", "Shared")
            </div>
        </div>
    </div>
</div>

code/IBV.EDC/IBV.EDC.Web/Views/ListSearch.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "_Layout.cshtml";
}

<div class="banner">
    <h1>@Model.Content.Name</h1>
</div>
@Html.Action("BreadcrumbTrail", "Shared")

<div class="list-results with-side-nav">
    <div class="container-2col">
        <div class="grid__col--8">
            @Umbraco.Field("nodeHeading", insertBefore: "<h1>", insertAfter: "</h1>")
            @Html.Action("ListResults", "List")
            @Html.Action("Pager", "List")
        </div>
        <div class="grid__col--4">
            <div class="side-content">
                @Html.Action("ListFiltersSide", "List")
            </div>
        </div>
    </div>
</div>